version: "3.0"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: "/var/www/app/docker/startup.sh"
    depends_on:
      - database
    environment:
      CF_INSTANCE_INDEX: '0'
      VCAP_APPLICATION: >
        {"name": "web", "application_id": "docker"}
      VCAP_SERVICES: >
        { "aws-rds": [{
            "name": "database",
            "credentials": {
              "db_name": "dashbaord",
              "host": "database",
              "password": "mysql",
              "port": "3306",
              "username": "root"
            }
          }],
          "user-provided": [{
            "name": "secrets",
            "credentials": {
              "ENCRYPTION_KEY": "not-a-real-key-from-vcap"
            }
        }
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/app:delegated
      - uploads:/var/www/app/uploads

  database:
    image: mysql:5.7
    volumes:
      - database_data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: dashboard

volumes:
  database_data:
  uploads:
