---
version: 2
jobs:
  integration:
    machine: true
    steps:
      - checkout
      - run:
          name: Build the application image
          command: make build
      - run:
          name: Install application dependencies
          command: make install-dependencies
      - run:
          name: Run the application
          command: make up
      - run:
          name: Run integration tests
          command: make integration-tests
  unit:
    machine: true
    steps:
      - checkout
      - run:
          name: Build the application image
          command: make build
      - run:
          name: Install application development dependencies
          command: make install-dev-dependencies
      - run:
          name: Run the application
          command: make up
      - run:
          name: Run unit tests
          command: make unit-tests
  deploy:
    docker:
      - image: 18fgsa/cloud-foundry-cli
        environment:
          CF_API: https://api.fr.cloud.gov
    steps:
      - checkout
      - deploy:
          name: Push to Cloud Foundry
          command: cf_deploy.sh dashboard sandbox-gsa bret.mogilefsky

workflows:
  version: 2
  commit:
    jobs:
      - integration
      - unit
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - integration
            - unit

