---
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: Build docker image
          command: docker-compose build app
      - run:
          name: Install composer dependencies
          command: bin/composer install --no-dev
      - run:
          name: Start docker-compose containers
          command: docker-compose up -d
      - run:
          name: Test with bats
          command: docker-compose exec app bats -r test/

workflows:
  version: 2
  commit:
    jobs:
      - build
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
