---
version: 2
jobs:
  integration:
    machine: true
    steps:
      - checkout
      - run:
          name: Build the application image
          command: make build
      - run:
          name: Install application dependencies
          command: make install-dependencies
      - run:
          name: Run the application
          command: make up
      - run:
          name: Run integration tests
          command: make integration-tests
  unit:
    machine: true
    steps:
      - checkout
      - run:
          name: Build the application image
          command: make build
      - run:
          name: Install application development dependencies
          command: make install-dev-dependencies
      - run:
          name: Run the application
          command: make up
      - run:
          name: Run unit tests
          command: make unit-tests

workflows:
  version: 2
  commit:
    jobs:
      - integration
      - unit
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - integration
      - unit
