---
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:apache-stretch
        environment:
          DB_NAME: dashboard
          DB_USER: root
          DB_PASSWORD: mysql
          DB_HOST: 127.0.0.1
          ENCRYPTION_KEY: not-secure-encryption-key
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_DATABASE: dashboard
    steps:
      - checkout
      - run:
          name: Set httpd document root
          command: |
            sudo sed -i 's.DocumentRoot /var/www/html.DocumentRoot /home/circleci/project.' /etc/apache2/sites-available/000-default.conf
      - run: sudo docker-php-ext-install mysqli
      - restore_cache:
          keys:
            - v1-composer-{{ checksum "composer.lock" }}
            - v1-composer-
      - run: composer --no-interaction install --no-dev
      - save_cache:
          key: v1-composer-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: Install bats-core
          command: |
            git clone https://github.com/bats-core/bats-core.git /tmp/bats-core && \
              cd /tmp/bats-core && \
              sudo ./install.sh /usr/local && \
              /bin/rm -rf /tmp/bats-core
      - run: 
          name: Run bats tests
          command: |
            bats -r test/


workflows:
  version: 2
  commit:
    jobs:
      - build

  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master

    jobs:
      - build
