---
name: Dashboard crawl-long

on:
  workflow_dispatch:
  schedule:
    - cron: '30 12 1 1,4,7,10 *'

jobs:
  dashboard-crawl-long-staging:
    name: dashboard long crawl (staging)
    environment: staging
    runs-on: ubuntu-latest
    container:
      image: cloudfoundry/cli:8
      env:
        org: gsa-datagov
        space: staging
        user: ${{secrets.CF_SERVICE_USER}}
        password: ${{secrets.CF_SERVICE_AUTH}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: auth
        run: ./cfauth.sh
      - name: crawl download
        run: cf run-task dashboard-stage --command "php public/index.php campaign status long-running full-scan"
  dashboard-crawl-long-prod:
    name: dashboard long crawl (production)
    environment: production
    runs-on: ubuntu-latest
    container:
      image: cloudfoundry/cli:8
      env:
        org: gsa-datagov
        space: prod
        user: ${{secrets.CF_SERVICE_USER}}
        password: ${{secrets.CF_SERVICE_AUTH}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: auth
        run: ./cfauth.sh
      - name: crawl download
        run: cf run-task dashboard --command "php public/index.php campaign status long-running full-scan"
