---
name: Dashboard crawl (daily)

on:
  workflow_dispatch:
  schedule:
    - cron: '15 4 * * *'

jobs:
  dashboard-crawl-staging:
    name: dashboard crawl (staging)
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: crawl download
        # pinned to cf7 until --wait is available for run-task on cf8...
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: cf run-task dashboard-stage --command "php public/index.php campaign status omb-monitored download" --wait --name dashboard-omb-monitored-download
          cf_org: gsa-datagov
          cf_space: staging
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: crawl full scan
        # pinned to cf7 until --wait is available for run-task on cf8...
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: cf run-task dashboard-stage --command "php public/index.php campaign status omb-monitored full-scan" --wait --name dashboard-omb-monitored-full-scan
          cf_org: gsa-datagov
          cf_space: staging
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
  dashboard-crawl-prod:
    name: dashboard crawl (production)
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: crawl download
        # pinned to cf7 until --wait is available for run-task on cf8...
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: cf run-task dashboard --command "php public/index.php campaign status omb-monitored download" --wait --name dashboard-omb-monitored-download
          cf_org: gsa-datagov
          cf_space: prod
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      - name: crawl full scan
        # pinned to cf7 until --wait is available for run-task on cf8...
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: cf run-task dashboard --command "php public/index.php campaign status omb-monitored full-scan" --wait --name dashboard-omb-monitored-full-scan
          cf_org: gsa-datagov
          cf_space: prod
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
