---
name: Dashboard crawl-long

on:
  workflow_dispatch:
  schedule:
    - cron: '30 12 1 1,4,7,10 *'

jobs:
  dashboard-crawl-long-staging:
    name: dashboard long crawl (staging)
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: crawl download
        # pinned to cf7 until --wait is available for run-task on cf8...
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: cf run-task dashboard-stage --command "php public/index.php campaign status long-running full-scan"
          cf_org: gsa-datagov
          cf_space: staging
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}

  dashboard-crawl-long-prod:
    name: dashboard long crawl (production)
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: crawl download
        # pinned to cf7 until --wait is available for run-task on cf8...
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: cf run-task dashboard --command "php public/index.php campaign status long-running full-scan"
          cf_org: gsa-datagov
          cf_space: prod
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
